added support for enable eth device on boot, added supprot for bringing interfaces up prproperly after new eth devices are added in the system-config-network

diff --git a/simple-installer/install_kazoo b/simple-installer/install_kazoo
--- a/simple-installer/install_kazoo
+++ b/simple-installer/install_kazoo
@@ -315,20 +315,32 @@ set_install_source(){
 set_interfaces_up(){
     local -a interfaces
     while read line; do 
-        if [[ $line =~ ^[0-9]:.* ]];then
-             local int=`cut -d' ' -f 2`;
-             interfaces+=(${int%%:.*})
+        if [[ $line =~ ^[0-9]:.* && $line =~ "state DOWN" ]];then
+             local int=`echo $line| cut -d' ' -f 2`;
+             interfaces+=(${int%%:*})
         fi
     done < <(ip link)
 
     dbg "Restarting networking with:${NC} service network restart"
-    service network restart
 
     for int in ${interfaces[@]}; do
-        dbg "bringing up interface ${red}${int}${NC}" 
-        ip link set $int up || error "interface $int failed to come up" 
-    done
+        local $answer=""
+        confirm "Interface $int is currently down, do you want to bring this up? [Y|N]"
+        if [[ $answer =~ [Yy] ]];then
+            dbg "bringing up interface ${red}${int}${NC}" 
+            ifup $int || error "interface $int failed to come up"
+        fi
 
+        grep -s ONBOOT "/etc/sysconfig/network-scripts/ifcfg-${int}"
+        if [[ $? -gt 0 ]];then
+            answer=""
+            confirm "Do you want to enable interface to start up $int on boot? [Y|N]"
+            if [[ $answer =~ [Yy] ]];then
+                dbg "setting interface ${red}${int}${NC} to enable on boot" 
+                echo  "ONBOOT=yes" >> "/etc/sysconfig/network-scripts/ifcfg-${int}"
+            fi
+        fi  
+    done
 }
 
 
