log_print should be piping output not redirecting

diff --git a/simple-installer/setup_common b/simple-installer/setup_common
--- a/simple-installer/setup_common
+++ b/simple-installer/setup_common
@@ -285,7 +285,7 @@ run_cmd(){
 
     while read line; do 
         echo -en "\r${ceol}${line:-}"
-    done < <(eval $cmd_final 2>&1 log_print || error "$error")
+    done < <(eval $cmd_final |& log_print || error "$error")
      echo
 
 }
