again with the truncating log file!

diff --git a/simple-installer/setup_packages b/simple-installer/setup_packages
--- a/simple-installer/setup_packages
+++ b/simple-installer/setup_packages
@@ -215,7 +215,7 @@ run_cmd(){
 
     while read line; do 
         echo -en "\r${ceol}${line:-}"
-    done < <(eval $cmd_final 2> $install_log || error "$error")
+    done < <(eval $cmd_final 2>> $install_log || error "$error")
      echo
 
 }
