better error handling, more sanity checks, common validation and nuclear uninstall script

diff --git a/simple-installer/setup_common b/simple-installer/setup_common
--- a/simple-installer/setup_common
+++ b/simple-installer/setup_common
@@ -2,8 +2,6 @@
 
 set -o nounset
 
-declare -a ip_addresses
-declare -a interfaces
 default_cookie=""
 system_hostname=""
 
@@ -36,6 +34,16 @@ warn(){
 }
 
 cookie_file="/etc/kazoo/erlang.cookie"
+ip_address_file="/etc/kazoo/kazoo.ip_address"
+
+#TODO: Add common definition for REGEX matches 
+#for valid url, IP address, port, hostname for use in setup scripts. 
+
+#validation regexes for use in ask 
+url_regex="^(https?:\/\/)?([0-9a-z\.-\.]+)([a-z\.]{2,6})?([:][0-9]+)?([\/\w\.-]*)*\/?$"
+ip_address_regex="^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$"
+fqdn_regex='(?=^.{4,255}$)(^((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\.)+[a-zA-Z]{2,63}$)'
+ip_fqdn_regex="$ip_address_regex|$fqdn_regex"
 
 
 #Safety stuff (must be root, lockfile functions, trap and clean_exit function)
@@ -76,27 +84,27 @@ check_lock(){
 clean_exit(){
     echo "Completed $0"
     clear_lock $lockfile
-    echo -e "${NC}"
+    echo -e -n "${NC}"
     trap - EXIT
     exit 0;
 }
 
 error_exit(){
-    echo -e "${red}ERROR: exiting due to: ${@:-"unknown error"}${NC}"
-    echo -e "${yellow}see ${NC}/var/log/kazoo_install.log${yellow} for details${NC}"
-    echo -e "${yellow}you can restart this script manually with ${green}$0 ${NC} "
+    error "exiting due to: ${@:-"unknown error"}"
+    echo 
+    echo -e "NOTE: ${yellow}you can restart this script manually with ${green}$0 ${NC}"
     clear_lock $lockfile
-    echo -e "${NC}"
+    echo -e -n "${NC}"
     trap - EXIT
     exit 1;
 
 }
 
 int_exit(){
-    echo -e "${yellow}EXITING: SIGINT|SIGQUIT (ctrl-C|ctrl-) received! ${NC}"
+    echo -e "${yellow}EXITING: due to user interrupt (ctrl-C|ctrl-\)! ${NC}"
     echo -e "${yellow}you can restart this script manually with ${green}$0 ${NC} "
     clear_lock $lockfile
-    echo -e "${NC}"
+    echo -e -n "${NC}"
     trap - EXIT
     exit 1;
 }
@@ -129,32 +137,45 @@ get_system_hostname(){
 ask_ip_selection(){
     local -a ip_addresses
     local -a interfaces
+    
+    if [ -e $ip_address_file ];then
+        ip_address=$(<$ip_address_file)
+        if [[ $ip_address =~ $ip_address_regex ]]; then
+            system_ip_address=$ip_address 
+            return 
+        else 
+            warn "The system IP address in $ip_address_file is not a valid ip!"
+        fi 
+        
+    fi
+
     get_interfaces
     get_system_ip 
 
     if [ ${#ip_addresses[@]:-} -eq 1 ];then
         system_ip_address=${ip_addresses[0]}
-        return
     elif [ ! ${#ip_addresses[@]:-} ];then
         warn "NO ip addresses are configured!"
         system_ip_address=""
         local system_ip_address_question="Please enter a system ip address you will be assigning to this server"
-        local system_ip_address_re="[0-9]+\.[0-9]+\.[0-9]\.[0-9]+"
+        local system_ip_address_re="$ip_address_regex"
         local system_ip_address_hint="Since you do not currently have an IP address, you can use this menu to add the IP you plan to assign after setup"
         local system_ip_address_ref="system_ip_address"
         ask system_ip_address
-        return 
+    else
+      PS3="Please select the IP address to use:"
+      select opt in ${ip_addresses}; do
+          case $opt in
+             *)
+               system_ip_address=$opt     
+               break
+               ;;
+          esac
+      done
     fi
+    
+    echo -n $system_ip_address >> $ip_address_file
 
-    PS3="Please select the IP address to use:"
-    select opt in ${ip_addresses}; do
-        case $opt in
-           *)
-             system_ip_address=$opt     
-             break
-             ;;
-        esac
-    done
 }
 
 set_value(){
@@ -175,7 +196,7 @@ set_value(){
 
     #run command and log output to $install_log
     dbg $debug_final
-    eval $cmd_final &> $install_log
+    eval $cmd_final &> $install_log || error_exit "Command $cmd_final failed"
 
     #verify command returned success response, throw error if failed
     if [[ $? -ne 0 ]];then
@@ -183,13 +204,18 @@ set_value(){
     fi
 }
 
+check_re(){
+   val=$1
+   re=$2
+   echo $val | grep -P "$re" &> $install_log || return 1
+   return 
+}
+
 #gets input for the user for $name parameter
 ask(){
    local name=$1
 
-   #this is one of the major problems with bash
-   #we use the name object to "dereference" the variables we need for this function
-   #if these are not defined above, we will explode thanks to -o nounset
+   #we use the name value to "dereference" the variables we need for this function
    local _question=\$"${name}_question"
    local _re=\$"${name}_re"
    local _ref=\$"${name}_ref"
@@ -204,10 +230,11 @@ ask(){
    read ANSWER
    
    #if invalid answer, we show them the hint and call ourselves with our args
-   if ! [[ $ANSWER =~ $re ]];then
+   if ! check_re $ANSWER $re ; then
       warn $hint
       ask $@
    fi
+
    eval $ref="$ANSWER"
 }
 
@@ -237,7 +264,6 @@ get_default_cookie(){
     fi 
     
     if ! [  ${default_cookie:-} ];then
-        echo "NO COOKIE FOUND --- GENERATING"   
         local answer
         confirm "Do you want to generate a new erlang cookie? [y|n]"
         if [[ $answer =~ ^[yY] ]];then
diff --git a/simple-installer/setup_packages b/simple-installer/setup_packages
--- a/simple-installer/setup_packages
+++ b/simple-installer/setup_packages
@@ -7,9 +7,8 @@ declare -A install_list
 lockfile="/var/lock/subsys/setup_kazoo.lockfile"
 . /opt/kazoo_install/setup_common
 
-trap clean_exit SIGHUP SIGTERM 
+trap error_exit SIGHUP SIGTERM EXIT
 trap int_exit SIGINT SIGQUIT
-trap clean_exit EXIT
 
 dir="/opt/kazoo_install/"
 
@@ -55,11 +54,11 @@ handle_args(){
 do_setup(){
     for package in ${!install_list[@]}; do
         package_setup="${dir}setup_${package}"
-        dbg "Running ${NC} $package_setup ${green} for ${NC} $package"
+        dbg "Running ${NC} $package_setup ${green}for package${NC} $package"
         if [[ -n $all_in_one ]]; then 
-           $package_setup -a
+           $package_setup -a || error_exit "package setup failed for $package in script: ${NC}$package_setup"
         else
-           $package_setup 
+           $package_setup || error_exit "package setup failed for $package in script: ${NC}$package_setup"
         fi
     done
 }
@@ -70,42 +69,43 @@ do_final_steps(){
         rm -rf /etc/haproxy/haproxy.cfg
         ln -s /etc/kazoo/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg
         dbg "Restart HAProxy to apply changes with: ${NC} service haproxy restart"
-        /sbin/service haproxy restart
+        /sbin/service haproxy restart || error_exit "haproxy restart failed"
     fi 
 
     #TODO: SETUP IP TABLES PER SERVICE!!!!!!
     warn "Dude, We are stopping IP tables, that means your shields are down brother, might wanna do something about it!!"
-    service iptables stop
+    service iptables stop 
 
     #start services
     dbg "Restart Rsyslog"
-    /sbin/service rsyslog restart
+    /sbin/service rsyslog restart || error "rsyslon failed to start"
 
 
-    if [[ ${install_list['bigcouch']:-}  || ${install_list['kazoo']:-}  || ${install_list['bigcouch']:-} ]];then
+    if [[ ${install_list['freeswitch']:-} ]];then
         dbg "Start EPMD with: ${NC} /usr/bin/epmd -daemon"
-        /usr/bin/epmd -daemon
+        /usr/bin/epmd -daemon || error_exit "epmd daemon failed to start"
+        dbg "Epmd status is: "
         netstat -ptlen | grep epmd
     fi 
 
     if [[ ${install_list['bigcouch']:-} ]];then 
         dbg "Restart Bigcouch to apply changes with:${NC} service bigcouch restart"
-        /sbin/service bigcouch restart
+        /sbin/service bigcouch restart || error_exit "Bigcouch restart failed"
     fi 
 
     if [[ ${install_list['rabbitmq']:-} ]];then 
-        dbg "Start RabbitMQ with: ${NC} service rabbitmq-server start"
-        /sbin/service rabbitmq-server restart
+        dbg "Start RabbitMQ with: ${NC} service rabbitmq-server restart"
+        /sbin/service rabbitmq-server restart || error_exit "Rabbitqm restart failed"
     fi 
 
     if [[ ${install_list['freeswitch']:-} ]];then 
         dbg "Start FreeSWITCH with: ${NC} service freeswitch restart"
-        /sbin/service freeswitch restart
+        /sbin/service freeswitch restart || error_exit "Freeswitch restart failed"
     fi 
 
     if [[ ${install_list['bigcouch']:-} ]];then 
         dbg "Restart Kamailio to apply the changes with: ${NC} service kamailio restart"
-        /sbin/service kamailio restart
+        /sbin/service kamailio restart || error_exit "Kamailio restart failed"
     fi
 
     if [[ ${install_list['kazoo']:-} ]];then 
@@ -113,12 +113,12 @@ do_final_steps(){
         /sbin/service kz-whistle_apps restart
 
         dbg "Start ecallmgr with: ${NC} service kz-ecallmgr restart"
-        /sbin/service kz-ecallmgr restart
+        /sbin/service kz-ecallmgr restart || error_exit "kz-ecallmgr restart failed"
 
         wait_apps_running
 
         dbg "Displaying whistle_apps status with: ${NC} service kz-whistle_apps status "
-        /sbin/service kz-whistle_apps status
+        /sbin/service kz-whistle_apps status 
     fi  
 
 
@@ -127,36 +127,36 @@ do_final_steps(){
 
     if [[ ${install_list['kazoo']:-} ]];then 
         dbg "Starting httpd"
-        /sbin/service httpd start
+        /sbin/service httpd restart || error_exit "httpd restart failed"
     fi
 
 
     if [[ ${install_list['bigcouch']:-} ]];then 
         dbg "Updating all Bigcouch views with: ${NC} sup whapps_maintenance blocking_refresh"
-        /opt/kazoo/utils/sup/sup whapps_maintenance blocking_refresh
+        /opt/kazoo/utils/sup/sup whapps_maintenance blocking_refresh || error_exit "sup whapps_maintenance blocking_refresh failed!"
 
         dbg "Importing media files with: ${NC} /opt/kazoo/utils/media_importer/media_importer /opt/kazoo/system_media/*.wav "
-        /opt/kazoo/utils/media_importer/media_importer /opt/kazoo/system_media/*.wav 
+        /opt/kazoo/utils/media_importer/media_importer /opt/kazoo/system_media/*.wav || error_exit "media import command failed"
 
         #Create new account
-        dbg "Create admin account with: ${NC} sup crossbar_maintenance create_account admin sip.${system_hostname} admin admin"
-        /opt/kazoo/utils/sup/sup crossbar_maintenance create_account admin "sip.${system_hostname}" admin admin
+        dbg "Created admin account with: ${NC} sup crossbar_maintenance create_account admin sip.${system_hostname} admin admin"
+        /opt/kazoo/utils/sup/sup crossbar_maintenance create_account admin "sip.${system_hostname}" admin admin || error_exit "Account creation failed"
     fi 
     
-    
-
-    echo "INSTALL COMPLETE: WELCOME TO KAZOO!"
+    if [[ ${install_list['kazoo-ui']:-} ]]; then
+        echo "You can access the kazoo-ui by going to http://$system_ip_address/kazoo-ui"
+    fi
 
 }
 
 check_lock
 handle_args $@
+ask_ip_selection
+get_system_hostname
 [ ${all_in_one:-} ] && generate_erlang_cookie
 do_setup
-get_system_hostname
 do_final_steps
-
-
+echo "INSTALL COMPLETE!"
 clean_exit
 
 
