testing the changes suggested by darren

diff --git a/simple-installer/setup_common b/simple-installer/setup_common
--- a/simple-installer/setup_common
+++ b/simple-installer/setup_common
@@ -128,7 +128,7 @@ int_exit(){
     exit 1;
 }
 
-#gets list of ethernet interfaces and puts in array interfaces
+#gets list of Ethernet interfaces and puts in array interfaces
 get_interfaces(){
     for interface in `ifconfig | grep Ethernet |cut -d" " -f1`;do
         interfaces+=("$interface")
@@ -192,6 +192,69 @@ ask_ip_selection(){
     echo -n $system_ip_address >> $ip_address_file
 
 }
+
+wait_apps_running(){
+    dbg "Waiting for whapps to start by polling: ${NC}/opt/kazoo/utils/sup/sup whapps_controller list_apps"
+
+    while
+    /opt/kazoo/utils/sup/sup whapps_controller list_apps &>> $install_log
+    (( $? != 0 ))
+    do
+        continue
+    done
+
+    dbg "Waiting for ecallmgr to start by polling: ${NC}/opt/kazoo/utils/sup/sup -necallmgr ecallmgr_maintenance list_fs_nodes"
+
+    while
+    /opt/kazoo/utils/sup/sup -necallmgr ecallmgr_maintenance list_fs_nodes &>> $install_log
+    (( $? != 0 ))
+    do
+        continue
+    done
+}
+
+################################################################################
+#  run_cmd NOTE:
+#  *_cmd and *_dbg are access commands and debug statements for use in set_value
+#  TOKEN is replaced using with the $value argument in set_value
+#  using variable expansion substring replacement
+################################################################################
+
+run_cmd(){
+    local name=$1
+    local value=${2:-}
+
+    #use $name to find variables we want
+    local _debug=\$"${name}_dbg"
+    local _cmd=\$"${name}_cmd"
+    local _error=\$"${name}_error"
+
+    #dereference same
+    local debug=`eval "expr \"${_debug}\""`
+    local cmd=`eval "expr \"${_cmd}\""`
+    local error=`eval "expr \"${_error}\""`
+
+    local debug_final=$debug
+    local cmd_final=$cmd
+    local error_final=$error
+
+    #replace TOKEN with $value
+    if [[ ${value:-} ]]; then    
+        debug_final=${debug//TOKEN/$value}
+        cmd_final=${cmd//TOKEN/$value}
+        error_final=${error//TOKEN/$value}
+    fi
+
+    #run command and log output to $install_log
+    dbg $debug_final
+
+    while read line; do 
+        echo -en "\r${ceol}${line:-}"
+    done < <(eval $cmd_final 2>> $install_log || error "$error")
+     echo
+
+}
+
 
 set_value(){
 
@@ -258,9 +321,6 @@ ask(){
     #  fqdn_regex - matches fully qualified domain names
     #  ip_fqdn_regex - matches ip OR fully qualified domain names
     ##################################################################################
-
-
-
 
    #we use the name value to "dereference" the variables we need for this function
     local _question=\$"${name}_question"
